### PR TITLE
add basic components

### LINKED ISSUE #15: Develop the component for submitting the feedback to the server
# User Story

As a developer I want to create some components, then I can use them for submitting the feedback and add backend function for testing purpose 

# Acceptance Criteria

Create components that user can input texts, and user able to show the text to the feedback field by click on the submit button.

# Pull Request

#26

### PR DESCRIPTION
**Pull request by zaks2318**
# Documentation

Closes #15 

This PR adds three components for submitting the feedback to the server. 
The first component is the InputTextBar.js. It contains a text area that users can enter text to it, and it also has a button that can submit the text to the App component.
The second component is the Feedback.js. it only has one function for now. It can show the texts that send from the InputTextBar.js.
The third component is the App.js. It is a container for components and future function. 

User story, acceptance criteria will show on the [related issue](https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/issues/15)

| Task Breakdown Description      | Approx. Time |
| ----------- | ----------- |
| Researching for AI feedback components     | 1 hour       |
| Setting up React Environment   | 1 hour        |
| design the components   | 1 hour        |
| coding for the components | 4 hours        |
| testing the components   | 0.5 hour        |
| change and fix some code after group discuss   | 1 hour        |
| add few comments and style to components | 0.5 hour        |
| Frontend Team Meets | 3 hours        |

# Gallery

##  How to deploy the functionality locally or in the cloud?
First, we need to use git bash to clone the branch from the [component branch](https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/tree/component)
Then, go to the floop_feedback folder, and run `npm i`, then run `npm start`.

2d0951aaee9489fe39e8724b586bc63

## How to configure the functionality?
It needs to use git command, so need to install git and node.js

## How to access the implemented functionality?
click on the textbox and start to type. Click submit button after done with typing. Then, your input text will show on the bottom.

382ac34ccf81c04e4e97bd0108eeeab

83df97bc5e9bf2bfad799d3fa7905cb

## What input to provide? What output is expected?
we can test with any text input, and the expected out for now is same text with input.

## Known troubleshooting steps
If the `npm start` is not working, try to install node.js and `npm init` on the terminal.

## Initial estimated time
10 hours

### CODE REVIEW

**Comment by CourtneyHoppus** [comment]
I believe this is what I was thinking about on this PR and running `npm init`:
https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/pull/16#issuecomment-1015741919
The `package-lock.json` for the app also needs to go in the `.gitignore` file.
This file changes when you add dependencies, scripts, and other things. It is very large. This is what is updated when we run `npm init`.
@toddysm

**Comment by CourtneyHoppus** [comment]
In the section _Known troubleshooting steps_ you have the command `npm i`, I believe it should be `npm init`.

**Review by CourtneyHoppus — CHANGES_REQUESTED** [review]
In the PR you have the command `npm i`, I believe it should be `npm init`.

**Review by ChrisNavoczynski — CHANGES_REQUESTED** [review]
To add, I'm unsure whether the index.js should have been deleted if needed in the future.  Otherwise Non-code related: Be sure to add your User story, acceptance criteria, and time to complete this task to your issue.

**Comment by zaks2318** [comment]
> 

I didn't delete the index.js, just change some of the codes in it.

**Comment by zaks2318** [comment]
> In the PR, in the _Known troubleshooting steps_, you have the command `npm i`, I believe it should be `npm init`.

get it, problem fixed.

**Review by ChrisNavoczynski — APPROVED** [review]
With the updated changes as requested, It's looks, to me, this PR meets the criteria for the Issue.

**Review by peterTorres7 — APPROVED** [review]
I was able to test the components and got the expected result following the steps provided. The only thing I see missing in an initial estimated time to complete this task, otherwise looks good!

**Review by CourtneyHoppus — CHANGES_REQUESTED** [review]
You are merging into the `frontend` branch, it should be `development`.

**Comment by zaks2318** [comment]
> You are merging into the `frontend` branch, it should be `development`.

Change back to development branch.

**Review by CourtneyHoppus — APPROVED** [review]

**Pull request merged**
