### PR TITLE
Research: Deploy React to S3 GitHub Action Instruction

### LINKED ISSUE #8: Investigate how to use GitHub actions to deploy React to S3
## User Story
As a developer I want to know how to deploy the React App to a S3 Bucket utilizing GitHub Actions

## Acceptance Criteria
- [x]  Research GitHub action implementation to learn about the process needed for deployment

## Pull Request
#27 
Documentation, and all other details can be found on the linked PR 

### Estimated Time:
8 hours 

### Actual time spent:
13 hours (This includes Frontend team meetups)
_(See hours breakdown on the PR, linked above)_

### PR DESCRIPTION
**Pull request by ChrisNavoczynski**
# Documentation:

Closes #8 

- This PR adds documentation based on research and testing on how to deploy React to an S3 bucket utilizing GitHub Actions
- This includes a frontend documentation folder to store these instructions as well as future issues on the frontend side that require a document/reference.
- The file instructions include:
   -  Creating an S3 Bucket _(while not directly part of this issue, were included)_
   -  Setting up the S3 Bucket for Web Hosting _(again not directly part of this issue, but included)_
   -  Configuring GitHub Actions workflow to deploy changes automatically. _(these have also been included below since this is the subject of this PR)_

## File Location
The `reactS3Action.md` file can be found in the `frontend/documentation` folder for reference.

## Time Spent on Issue:
| Task Breakdown Description | Approx. Time |
| ------------- | ------------- |
| Researching Deployment Resources | 2 hrs |
| Setting up React  Environment| 1 hr  |
| Compile the References to one easy to follow instruction  | 0.5 hr  |
| Testing Part 1: Create a test Repo, and React App | 1 hr  |
| Testing Part 2: Create a test S3 Bucket | 0.5 hr  |
| Testing Part 3:  Setup the Github Secrets and Workflow | 2 hrs | 
| Create the .md file and documentation folder in the frontend folder | 2 hrs |
| Create the PR with additional information and follow-along screenshots | 1 hr |
| Frontend Team Meets (as of 1/24/2022) | 3 hrs (total of all meetings)|

# Gallery & GitHub Action specific Instruction:

## On the GitHub Repo:
1. Click on the __Settings__ Tab.
2. Select __Secret__ on the left side menu
3. Click on __New Secret__ to add a secret providing _Name_ and _Value_:

 
Secrets

______________________

### Create key/value pairs for the following sensitive information:

| Name:          | Value:         |
|:---------------|:---------------|
|AWS_ACCESS_KEY_ID| your-aws-acess-key-id |
|AWS_SECRET_ACCESS_KEY| your-aws-secret-access-key |
|AWS_REGION| us-west-2 or other region |
|AWS_PRODUCTION_BUCKET_NAME| your-aws-bucket|

_____________________

### Be sure to note the names of the keys:
GitHubActions

______________________

### How the secrets will show once submitted:
RepoSecrets

______________________

## Setup GitHub Actions
1. While in the GitHub repo, click on the _Actions_ tab
2. On the __Actions__ page, click on the "__Set up this workflow__" or __Set up a workflow yourself__ button. _This takes you to a new page with a web editor with some container code which can be deleted_
3. 
GitHubActions2

______________________

3. Change "__blank.yml__" to an appropriate name (like s3-deploy).
4. Copy and Paste the code snippet into the editor: _NOTE: This is a general format and modifications based on the Repo and Bucket setup may slightly change in deployment settings_

gitWorkflow

_______________________

### What this file obtains:
The file is made of 3 different parts to help with the understanding:
* __name:__  The name of the Workflow
* __on:__ what triggers the Workflow, in this case the workflow will run anytime you __push__ code to the required __development branch__. _(It will trigger again when pushed to __master__ but no code will be directly pushed to __master__ in this specific project)_
* __jobs:__ Workflow run making up one or more jobs and they run parallel by default:
    * __steps:__ A job contains a sequence of tasks.. Steps run commands nad actions in your repo.
    * __actions/checkout@v2:__ Checks out the repo so workflow can access it.
    * __aws-actions/configure-aws-credentials@v1:__ This configures AWS credentials & region environment for use in other GitHub Actions
    * __Build React App:__ Installs node packages and runs the build in the __package.json__ file, and creates a __dist__ folder in the root directory.
    * __Deploy app build to S3 bucket:__  This deploys the newly created build to S3 bucket _bucket-name_ (replace with the name of the created S3 bucket)

To save, click on the __Start Commit__ then __Commit New File__.
Doing so will:
* Save the Action creating a .github directory with a workflows directory in it.
* It will contained the file s3-deploy (or whatever name assigned to it)
* Trigger the actions assigned.

 
WorkflowAdded

______________________________

## Troubleshooting:
*  Certain IAM permissions may be needed on the creation of the S3 bucket, utilizing the correct S3 bucket creation format
* As mentioned in the documentation, setting up the .yaml build file may require some additional steps in the jobs portion than what was added to the instruction. 
_(See documentation file for more details)_

### CODE REVIEW

**Review by zaks2318 — APPROVED** [review]
looks good and very detail, if can add some Known troubleshooting steps to the documentation will better!

**Review by peterTorres7 — APPROVED** [review]
The documentation is easy to follow and nicely detailed. Good job!

**Comment by ChrisNavoczynski** [comment]
Thank you guys! 

- @zaks2318 I added some troubleshooting tips at the end of the PR 
- @peterTorres7 I added estimated time on the connected Issue.

**Review by CourtneyHoppus — CHANGES_REQUESTED** [review]
This PR pushes more than the document that was created to fulfill the connected issue.
I believe it was based off a branch that has not been merged yet, and contains those files as well.
Their is also a `.vscode` file being pushed, I believe those are your personal editor settings, so they should not be included.

**Comment by ChrisNavoczynski** [comment]
Deleted the requested .vscode settings.json file that should not be part of the push.

**Review by CourtneyHoppus — APPROVED** [review]

**Pull request closed without merging**
