### PR TITLE
Simple lambda

### PR DESCRIPTION
**Pull request by TurkiBK**
Pleas someone review my PR.

### CODE REVIEW

**Comment by alasali1** [comment]
The Lambda API handles POST request, and updates mock data in server.

**Review by alasali1 — APPROVED** [review]
This POST request seems to work, and the link for your lambda function shows that the mock data does get Posted to the server. Good work.

**Review by Annelisebx — APPROVED** [review]
Lambda function created for POST requests

**Comment by TurkiBK** [comment]
I merge the first lambda version after it get 2 reviews .

**Pull request merged**
