### PR TITLE
Create deploy-lambda in GitHub actions

### LINKED ISSUE #24: Create a GitHub action to deploy the code handling POST requests to the Lambda function resource

### PR DESCRIPTION
**Pull request by Annelisebx**
_**Incomplete**_
Closes #24 

### Description
Created a GitHub Action using .github/workflows yml file. This Action is triggered when changes are pushed to my issue branch ab-24.  The Action deploys the code to the aws lambda function that was created.  

### Testing 
image
Creates actions in GitHub Actions which runs when a change is pushed to the ab-24 branch

- Action does not successfully run !!

### CODE REVIEW

**Comment by KristinJJ** [comment]
Hi @Annelisebx, I noticed that the node_modules are included in your PR. The node_modules usually aren't included in PRs since it makes it hard to notice any changes that you've added in your PR, and the node_modules also add to the project file size. [How to gitignore node_modules](https://sebhastian.com/git-ignore-node_modules/)

**Review by CourtneyHoppus — CHANGES_REQUESTED** [review]
This PR is changing 104 files. I don't believe that is the intent. Besides Kristin pointing out about node_modules, it looks like some other app building files.

**Comment by Annelisebx** [comment]
I removed a lot of folders and the PR is down to 6 files. I think only the one file I created/updated needs to be included. Can I delete the 5 other files directly from this PR and I can pull them again from development branch?

**Comment by CourtneyHoppus** [comment]
> I removed a lot of folders and the PR is down to 6 files. I think only the one file I created/updated needs to be included. Can I delete the 5 other files directly from this PR and I can pull them again from development branch?

Your commit history shows the deletes, I am not sure if this will mess up the development branch.  For our group, we closed the original PR, started a new branch based off of the current development branch, and added our relevant files to the new branch. We copied and pasted the old PR info into new ones. We didn't want there to be a history of deletes.

**Review by ChrisNavoczynski — COMMENTED** [review]
Besides the changes and requests Kristin and Courtney mentioned.

I believe, and I base this on the github action I too had to create, but I think you need to add the `development` branch under current branch for this action to still work once your branch is pushed into development  (line 8).
ymlactionlambda

**Comment by Annelisebx** [comment]
> Besides the changes and requests Kristin and Courtney mentioned.
> 
> I believe, and I base this on the github action I too had to create, but I think you need to add the `development` branch under current branch for this action to still work once your branch is pushed into development (line 8). ymlactionlambda

great catch, thank you

**Comment by Annelisebx** [comment]
Closing pull request. See new [PR 65](https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/pull/65)

**Pull request closed without merging**
