### PR TITLE
Swagger specification for AI feedback component

### LINKED ISSUE #5: Create the Swagger specification for the application
User Story

As a developer, I want to write a swagger specification that can handle HTTP requests for the AI Feedback component.

### Estimated time to complete
16 hours

### Acceptance Criteria
- [x] Create a YAML document with POST and GET requests
    - [x] Return 200 for GET and 201 for POST on Postman

### Pull Request
#20

### PR DESCRIPTION
**Pull request by alasali1**
Rough swagger specification defining feedback resource, and paths for HTTP requests.
Closes #5

### CODE REVIEW

**Review by dale108 — APPROVED** [review]
This will have to change once Cyrus and other finish their work (for instance, I think that we will want to keep track of tags) but for an initial pass, this looks good.

**Comment by alasali1** [comment]
> This will have to change once Cyrus and other finish their work (for instance, I think that we will want to keep track of tags) but for an initial pass, this looks good.

Got it. Thank you for feedback.

**Comment by alasali1** [comment]
User Story:

Create a Swagger specification for AI feedback component, feedback resource
Estimating Time:

2 hours
Acceptance Criteria:

    Create a YAML document with POST GET PUT and DELETE requests

**Review by CourtneyHoppus — COMMENTED** [review]
I don't think the host and the basepath are correct, this looks like something from the swagger editor.
I do not understand the purpose of the get request.
My understanding is that we are only posting feedback to the assignment. The response to that request will be the coaching on that feedback or an error.
I am also a little confused on the seen property being required.

**Comment by alasali1** [comment]
> I don't think the host and the basepath are correct, this looks like something from the swagger editor. I do not understand the purpose of the get request. My understanding is that we are only posting feedback to the assignment. The response to that request will be the coaching on that feedback or an error. I am also a little confused on the seen property being required.

Thank you for the feedback. I am going to fix the seen property and ID being required, because the ID should be generated by POST, and the seen property does not need to be required. The get request is more like a rough draft test to see that the feedback endpoint is working properly it will be removed and I will add more endpoints as the project moves along. I was not sure which host/basepath to point the API. So for testing purposes I kept the one generated from the swagger editor.

**Pull request merged**
