### PR TITLE
Update the API to return meaningful feedback

### LINKED ISSUE #88: Update the API to return meaningful information to the UI
Meaningful information is the following. Based on the input from the React UI we need to do the following:

- Break down the input in sentences
- Determine if each sentence is a question/statement/garbled text
- Determine the sentiment of each sentence

The API should return this information as a JSON response to the React UI. 

# User Story
As a user, I want to receive a meaningful response from the feedback that is sent for analysis

# Time to complete
Estimated: 8 hours
Actual: 11 hours

# Acceptance Criteria
- [x] Accept input containing "feedback" from the React UI
- [x] Breakdown the feedback in the lambda function into an array of objects
  - [x] Determine the type of sentence based on punctuation
  - [x] Determine the sentiment of each sentence
- [x] API Gateway should trigger the Lambda function to return a response containing a meaningful response

# Activities Documentation

| Date  | Activity | Time Spent |
| ------------- | ------------- | ------------- |
| 02/22/2022 | Update JSON response | 4 hr  |
| 02/26/2022 | Update lambda function to breakdown feedback into sentences | 2 hr  |
| 02/28/2022 | Update lambda function to determine sentence punctuation and sentiment | 2 hr  |
| 02/28/2022 | Update API Gateway to return response and troubleshoot with @mfern08  | 2 hr  |
| 02/28/2022 | Write/update documentation | 1 hr  |

# Pull Request
#109

### PR DESCRIPTION
**Pull request by KristinJJ**
Closes #88 

# Description 
As a user, I want to receive a meaningful response from the feedback that is sent for analysis.

# Gallery
Testing in Postman
Screen Shot 2022-02-28 at 11 02 33 PM

Testing in cURL
Screen Shot 2022-02-28 at 11 10 08 PM

# Tested
- Postman 
- cURL

# Testing
## Prerequisites 
- [ ] Postman or ability to run cURL command in the command line.

## Testing in Postman
- [ ] Open [Postman](https://www.postman.com/)
- [ ] Open a new request and select POST from the drop down menu.
- [ ] Enter `https://d5z72uewg7.execute-api.us-west-2.amazonaws.com/test/kj-6exxg-20220222-lambda` as the request URL.
- [ ] Select JSON from the drop down menu.
- [ ] Open the Body tab and enter `{
  "feedback": "YOUR_SENTENCES_HERE"
}`
- [ ] Hit the Send button to view the response JSON.

## Testing in cURL
- [ ] Open a terminal window.
- [ ] Run `curl -d ‘{“feedback": "YOUR_SENTENCES_HERE“}’ -H “Content-Type: application/json” -X POST https://d5z72uewg7.execute-api.us-west-2.amazonaws.com/test/kj-6exxg-20220222-lambda`
- [ ] View the response JSON.

# Known Issues
- If your feedback is not in the format `{
  "feedback": "YOUR_SENTENCES_HERE"
}` in Postman the lambda function will not know how to process the feedback.

- Sentences without ending punctuation of either a period (.), exclamation point (!), or question mark (?), are not considered full sentences and are unable to be analyzed.

### CODE REVIEW

**Review by dansjack — COMMENTED** [review]
If you give this route feedback that doesn't have punctuation, it returns an empty array. If that's intentional or out of scope for this PR, let me know and I'll approve!

image

**Comment by KristinJJ** [comment]
> If you give this route feedback that doesn't have punctuation, it returns an empty array. If that's intentional or out of scope for this PR, let me know and I'll approve!
> 
> image

Thanks for the feedback Dan, I will add a condition where if there are not sentences with punctuation something will be returned to the user to let them know

**Comment by KristinJJ** [comment]
> > If you give this route feedback that doesn't have punctuation, it returns an empty array. If that's intentional or out of scope for this PR, let me know and I'll approve!
> > image
> 
> Thanks for the feedback Dan, I will add a condition where if there are not sentences with punctuation something will be returned to the user to let them know

@dansjack Added a condition to the JSON response let the user know why their feedback was unable to be analyzed!

**Review by dansjack — APPROVED** [review]
Works as expected, passing a string with no punctuation returns an error

**Review by alasali1 — APPROVED** [review]
After doing the tests on Postman, everything seems to be working correctly. The error checking coincides with the errors on postman to force the user to enter meaningful feedback. Good work.

**Pull request merged**
