### PR TITLE
frontend set up

### LINKED ISSUE #1: Create a folder for the React app named frontend and initialize the app
Estimated Time: 2 hours 
This is due to needing to research how to initialize the app and then going through the initializing process.

### PR DESCRIPTION
**Pull request by TimnLyt**
### Issue Closed:
closes #1 

_**Acceptance Criteria and Time Spent/Estimated should be found in the issue mentioned above.**_

### In order to test the app:
Step 1: Clone the repo on personal _**machine.**_
Step 2: Change directory into floop_feedback folder by typing cd in terminal.
Step 3: Type npm start in terminal to run the application.
Step 4: Confirm browser opens up automatically and Launches application on a new window.

### Documentation:

**_The src file is where all development will take place_** 

- **_App.js_** is all the visuals that will be seen by the user on the web.
- **_App.css_** will have all the specifications for how elements render on the page.
- **_node_modules_** file will hold all the modules needed to run the app (held inside the .gitignore file)
- **_public_** file should hold anything such as text, icons and images.
- **_.gitignore_** will not push any files listed in this folder onto gihub.
- **_package.json_** and **_package-lock.json_** should store the dependencies needed to run the app.
- **_components_** the components file should consists of a collection of UI components like buttons, modals, inputs, loader, etc.

### Gallery:

Screenshot (357)

Screenshot (363)

Screenshot (361)

Screenshot (365)

Screenshot (366)

### Troubleshooting Steps:
If you run into problems when typing `npm start` to start the app,  try running `npm i` (npm install) in terminal to see if that solves the issue.

### In order to start the app:
You have to type `npm start` when in the src file. Then the application should open up in a new window.

### Application Running:

Screenshot (366)

### Outcome:

Screenshot (363)

### CODE REVIEW

**Comment by CourtneyHoppus** [comment]
I think we need to close this. If I recall from our web development course, we want to add `/nodemodules` to the `.gitignore` file. Then when we work in our local environment we run `npm init` to add the appropriate files to  `/nodemodules`. When additional dependencies or items are added to the package.lock file, we would run `npm init` again to bring the appropriate changes into our local environment.

**Comment by CourtneyHoppus** [comment]
I think the first line `closes test #1` should be `closes #1`

**Comment by TurkiBK** [comment]
"we would **run npm init** again to bring the appropriate changes into our local environment.
Any insight/guidance @toddysm would be appreciated."
do  you mean npm install?

**Comment by CourtneyHoppus** [comment]
@TurkiBK I don't think so, you aren't installing anything to the app, you are initializing it.

**Review by ChrisNavoczynski — APPROVED** [review]
- React app was functioning when I created a branch off of it.  
- Folder structure is organized
- Documentation was mentioned in class and looks good.

**Review by peterTorres7 — CHANGES_REQUESTED** [review]
@TimnLyt I think it is `npm i`, not `npm init`. It would installs the packages/modules and generate the needed folders that would be needed to run the app if they are missing . Also, don't we need a `components` folder?

**Comment by CourtneyHoppus** [comment]
Yes @peterTorres7 you are correct, I am sorry I was wrong.

**Comment by peterTorres7** [comment]
All good @CourtneyHoppus! It's not about being right or wrong, but learning together.

**Comment by ChrisNavoczynski** [comment]
I believe JiaJun created the components folder @peterTorres7 .  Once Tim makes the correction to this PR  ( change `npm  init` to `npm i`) and it gets approved and merged, JiaJun will be able to merge his PR with the components folder.

**Comment by TurkiBK** [comment]
@peterTorres7 ,  npm I , it is a short cut for npm install .When you create the Nodejs , you use amp init to create apps, and when you want to install model , you use npm install or npm I to install a model.Also, if your work on a team and some add a module that you do not have , npm just will install module that you missed on you app.

**Review by peterTorres7 — APPROVED** [review]
I see the change to `npm i`. Good job!

**Pull request merged**
