### PR TITLE
update script to write directly to S3

### PR DESCRIPTION
**Pull request by dale108**
Update to write directly to S3 from floop data collection script. I added some functionality so that the input steps can be bypassed by passing parameters to the script directly from the terminal like so:
`python3 floop_data_collection.py <path to your floop firebase pem file> <aws_access_key_id> <aws_secret_access_key>` 

For example, the path to my floop firebase pem file is: /Users/daleberg/Downloads/floop-firebase-development-firebase-adminsdk-g8bpy-8c72987529.json 

If you need help finding your key, you can follow the docs here: https://aws.amazon.com/blogs/security/wheres-my-secret-access-key/

You can confirm that the file was uploaded by checking the `floop-dataset` bucket, and looking for the file `floopData<$time_and_date_uploaded>.json`

Please let me know if you have any questions! I'll be happy to answer them. 

This PR fulfills requirements in https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/issues/44

### CODE REVIEW

**Comment by KristinJJ** [comment]
Hi @dale108, I am having some trouble creating the pem file for the floop database. Is there a specific method you would recommend? When I try and generate a private key file, I get an error message.

Floop Firebase error message:
Screen Shot 2022-02-07 at 4 43 02 PM

**Comment by dale108** [comment]
> Hi @dale108, I am having some trouble creating the pem file for the floop database. Is there a specific method you would recommend? When I try and generate a private key file, I get an error message. [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/auth-server)
> 
> Floop Firebase error message: Screen Shot 2022-02-07 at 4 43 02 PM

Hey Kristin! you can go to the floop firebase app here:https://console.firebase.google.com/u/0/project/floop-firebase-development/overview

then go to project settings here: 
image

Then on the "service accounts" tab, you can generate a private key:
image


that should download a handy json file with your credentials!

**Comment by KristinJJ** [comment]
Hmm still getting the same error, @dansjack do I need to have updated permissions to create a Floop Firebase access key?
Screen Shot 2022-02-07 at 5 26 33 PM

**Comment by dansjack** [comment]
Hi @KristinJJ, this appears to be a Firebase issue. I can't create a new key either! Can you try again tomorrow and see what happens? If it comes to it, I can upload a key to the dev environment to S3.

**Review by dansjack — APPROVED** [review]
Well done! Floop data (limit 10 text records) was uploaded to the floop-data S3 bucket.

I appreciate all the useful comments in the script

**Comment by KristinJJ** [comment]
> Hi @KristinJJ, this appears to be a Firebase issue. I can't create a new key either! Can you try again tomorrow and see what happens? If it comes to it, I can upload a key to the dev environment to S3.
> 
> 
> 
> 

Oh man, Firebase issue! Yes I can try again tomorrow and let you know if I'm able to generate a key or not then.

**Review by KristinJJ — APPROVED** [review]
Hi @dale108, the script worked and I could see the output in the S3 bucket as described!

**Pull request merged**
