### PR TITLE
Sage maker clustering

### PR DESCRIPTION
**Pull request by Lola2018**
Linked to issue #45

### CODE REVIEW

**Comment by dale108** [comment]
How should I test this? should I load it into a Jupyter Notebook and try to execute it?

**Comment by Lola2018** [comment]
> How should I test this? should I load it into a Jupyter Notebook and try to execute it?

yes

**Comment by Lola2018** [comment]
> > How should I test this? should I load it into a Jupyter Notebook and try to execute it?
> 
> yes

yes, go to sage maker and run it in the Jupiter

**Review by dale108 — APPROVED** [review]

**Comment by dale108** [comment]
this is ok for now, but definitely something that we should iterate on in the future

**Review by eyerusalemdani — APPROVED** [review]
It is ok for me.

**Pull request merged**
