### PR TITLE
add data collection script

### PR DESCRIPTION
**Pull request by dale108**
Simple script to pull comment data from the floop firebase. Not that we do not have access to their production org, so this will only work for dev. 

how it works:
- go to the floop firebase account and generate a cert file
- run the script, and input the path to the cert file you generated in the previous step 
- the script will generate a file, `floop_data.json` upon completion

### CODE REVIEW

**Review by CyrusSassan — CHANGES_REQUESTED** [review]
This script looks not a script that exported the floop_data_15k.json file, to do so you need to ask @dansjack  a permission and credentials and test the script if working on the Firebase; or if you do not receive permission, you can change the script accordingly. getting permission is good, because we might need further manipulation.

**Comment by dale108** [comment]
Hi Cyrus, I passed this script to Dan, and he ran the code against Floop's production database, with whatever changes needed to be made to account for the differences in schema between dev and prod (they are not identical, in Floop's case). They should not give us credentials to their production environment, and we should not need to run the script again to

**Review by ZenSorcere — APPROVED** [review]
Looks like we've got everything in place--proper filtering, no duplicate entries.

Approved!

**Review by dansjack — APPROVED** [review]
Script works, returns appropriate data.

**Pull request merged**
