### PR TITLE
uploading investigation of AWS technology that can run clustering alg…

### PR DESCRIPTION
**Pull request by Lola2018**
### Task Description
Research options for AWS algorithms that do clustering with Dynamo DB.
### Saved File
under the name of InvestigateAWS.md 
### Time Spent
Approximately 8 hours to find algorithms and evaluate the usefulness of the algorithms. Took some time to try and understand and decipher how each clustering method works and the scenarios that each clustering algorithm applies to.

### CODE REVIEW

**Review by CyrusSassan — APPROVED** [review]
I approve because of DAX clustering.

**Comment by Abenezer1041** [comment]
Make sure you link your pull request to issue.

**Review by Abenezer1041 — APPROVED** [review]

**Comment by dale108** [comment]
This work is in connection with this ticket: https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/issues/14

**Comment by KristinJJ** [comment]
Research looks good to me! To get full credit for this issue, make sure that all the following criteria is met:

```
·       Task must be created and appear on the project board

·       Task must be tagged with the proper labels (team and bug/task)

·       Task must be tagged with the proper milestone

·       Task must be assigned to the responsible developer

·       Task must be in In Progress state while in development

·       Task must be in Done state at the end of the sprint
```

**Pull request merged**
